nouns = """people – M pueblo
. time – M tiempo
. year – M año
. thing – F cosa
. way – M camino
. day – M día
. man – M hombre
. state – M estado
. lot – M lote
. woman – F mujer
. country – M país
. life – F vida
. question – F cuestión
. president – M presidente
. child – M niño
. week – F semana
. world – M mundo
. kind – M tipo
. case – M caso
. problem – M problema
. fact – M hecho
. family – F familia
. story – F historia
. point – M punto
. government – M gobierno
. money – M dinero
. issue – F cuestión
. part – F parte
. morning – F mañana
. guy – M chico
. number – M número
. job – M trabajo
. night – F noche
. right – M derecho
. school – F escuela
. place – M lugar
. war – F guerra
. kid – M niño
. month – M mes
. book – M libro
. hour – F hora
. show – M show
. police – F policía
. program – M programa
. party – M partido
. law – F ley
. word – F palabra
. person – F persona
. home – M hogar
. business – M negocio
. friend – M amigo
. company – F empresa
. side – M lado
. tax – M impuesto
. democrat – M demócrata
. group – M grupo
. moment – M momento
. break – F ruptura
. idea – F idea
. member – M miembro
. system – M sistema de
. minute – M minuto
. reason – F razón
. campaign – F campaña
. work – F obra
. nation – F nación
. congress – M congreso
. mother – F madre
. force – F fuerza
. health – F salud
. back – F parte de atrás
. area – F zona
. name – M nombre
. report – M informe
. hand – F mano
. line – F línea
. end – M fin
. court – F corte
. care – M cuidado
. couple – F pareja
. house – F casa
. american – F americana
. father – M padre
. situation – F situación
. car – M coche
. parent – M padre
. administration – F administración
. drug – F droga
. city – F ciudad
. sense – M sentido
. policy – F política
. office – F oficina
. decision – F decisión
. power – M poder
. plan – M plan
. leader – M líder
. information – F información
. election – F elección
. movie – F película
. death – F muerte
. air – M aire
. call – F llamada
. community – F comunidad
. look – F mirada
. evidence – F evidencia
. girl – F chica
. doctor – M médico
. vote – M voto
. video – M video
. picture – F imagen
. room – F habitación
. economy – F economía
. phone – M teléfono
. history – F historia
. sort – M tipo
. boy – M niño
. crime – M crimen
. process – M proceso de
. wife – F esposa
. music – F música
. water – M agua
. service – M servicio
. record – M registro
. security – F seguridad
. talk – F charla
. mind – F mente
. head – F cabeza
. candidate – M candidato
. official – M funcionario
. camera – F cámara
. student – M estudiante
. attack – M ataque
. chance – F oportunidad
. game – M juego
. baby – M bebé
. south – M sur
. change – M cambio
. trial – M juicio
. body – M cuerpo
. market – M mercado
. stuff – F cosas
. interest – M interés
. weapon – M arma
. heart – M corazón
. son – M hijo
. team – M equipo
. town – F ciudad
. television – F televisión
. will – F voluntad
. troop – F tropa
. judge – M juez
. action – F acción
. answer – F respuesta
. position – F posición
. view – F vista
. difference – F diferencia
. food – F comida
. daughter – F hija
. race – F carrera
. deal – M acuerdo
. street – F calle
. price – M precio
. message – M mensaje
. control – M control
. debate – M debate
. officer – M oficial
. film – F película
. level – M nivel
. effort – M esfuerzo
. relationship – F relación
. correspondent – M corresponsal
. ground – M terreno
. piece – F pieza
. husband – M marido
. budget – M presupuesto
. jury – M jurado
. reporter – M reportero
. weekend – M fin de semana
. matter – F materia
. age – F edad
. gun – F pistola
. peace – F paz
. murder – M asesinato
. role – M papel
. investigation – F investigación
. experience – F experiencia
. hospital – M hospital
. eye – M ojo
. director – M director
. future – M futuro
. face – F cara
. oil – M aceite
. result – M resultado
. public – M público
. lawyer – M abogado
. poll – F encuesta
. second – F segunda
. opportunity – F oportunidad
. industry – F industria
. brother – M hermano
. statement – F declaración
. fire – M fuego
. love – M amor
. rate – F tasa
. effect – M efecto
. song – F canción
. event – M evento
. charge – F carga
. support – M apoyo
. radio – F radio
. building – M edificio
. bank – M banco
. victim – F víctima
. door – F puerta
. interview – F entrevista
. scene – F escena
. rest – M resto
. press – F prensa
. attention – F atención
. choice – F elección
. speech – M discurso
. patient – M paciente
. truth – F verdad
. road – F carretera
. term – M término
. site – M sitio
. worker – M trabajador
. professor – M profesor
. letter – F letra
. reform – F reforma
. concern – F preocupación
. folk – F gente
. sex – M sexo
. study – M estudio
. college – F universidad
. voter – M votante
. wall – F pared
. evening – F noche
. meeting – F reunión
. voice – F voz
. audience – F audiencia
. violence – F violencia
. rule – F regla
. star – F estrella
. test – F prueba
. education – F educación
. trouble – M problema
. risk – M riesgo
. prison – F prisión
. guest – M invitado
. class – F clase
. society – F sociedad
. soldier – M soldado
. plane – M plano
. amount – F cantidad
. help – F ayuda
. cost – M costo
. authority – F autoridad
. foot – M pie
. period – M período
. feeling – F sensación
. step – F etapa de
. cause – F causa
. tape – F cinta
. threat – F amenaza
. opinion – F opinión
. organization – F organización
. type – M tipo de
. conversation – F conversación
. disease – F enfermedad
. operation – F operación
. cancer – M cáncer
. magazine – F revista
. governor – M gobernador
. pressure – F presión
. majority – F mayoría
. research – F investigación
. character – M carácter
. station – F estación
. crisis – F crisis
. expert – M experto
. blood – F sangre
. chairman – M presidente
. argument – M argumento
. list – F lista
. dog – M perro
. computer – M ordenador
. beginning – M principio
. insurance – M seguro
. field – M campo
. sister – F hermana
. mistake – M error
. player – M jugador
. energy – F energía
. paper – M documento
. space – M espacio
. store – F tienda
. agreement – M acuerdo
. responsibility – F responsabilidad
. lady – F dama
. order – M orden
. summer – M verano
. product – M producto
. value – M valor
. stock – F acción
. intelligence – F inteligencia
. teacher – M profesor
. agency – F agencia
. trade – M comercio
. conference – F conferencia
. cell – F célula
. church – F iglesia
. comment – M comentario
. source – F fuente
. past – M pasado
. cut – M corte
. thought – M pensamiento
. credit – M crédito
. hope – F esperanza
. sign – M signo
. career – F carrera
. marriage – M matrimonio
. condition – F condición
. witness – M testigo
. technology – F tecnología
. stage – F etapa de
. staff – M personal
. arm – M brazo
. mission – F misión
. art – M arte
. actor – M actor
. battle – F batalla
. top – F parte superior
. citizen – M ciudadano
. author – M autor
. reaction – F reacción
. gentleman – M caballero
. leadership – M liderazgo
. fear – M miedo
. example – M ejemplo
. language – M idioma
. need – F necesidad
. justice – F justicia
. discussion – F discusión
. border – F frontera
. animal – M animal
. detail – M detalle
. response – F respuesta
. network – F red
. movement – M movimiento
. use – M uso
. male – M macho
. capital – F capital
. hearing – F audiencia
. standard – F norma
. benefit – M beneficio
. table – F tabla
. treatment – M tratamiento
. agent – M agente
. card – F tarjeta
. shot – M disparo
. board – M tablero
. reality – F realidad
. sir – M señor
. land – F tierra
. project – M proyecto
. light – F luz
. image – F imagen
. century – M siglo
. page – F página
. success – M éxito
. sound – M sonido
. impact – M impacto
. pain – M dolor
. season – F temporada
. individual – M individuo
. sport – M deporte
. studio – M estudio
. decade – F década
. challenge – M desafío
. dream – M sueño
. newspaper – M periódico
. floor – M piso
. fight – F lucha
. safety – F seguridad
. act – M acto
. trip – M viaje
. course – M curso
. possibility – F posibilidad
. freedom – F libertad
. fund – M fondo
. seat – M asiento
. bomb – F bomba
. form – F forma
. executive – M ejecutivo
. minister – M ministro
. deficit – M déficit
. development – M desarrollo
. flight – M vuelo
. secretary – M secretario
. committee – M comité
. consumer – M consumidor
. rock – F roca
. figure – F figura
. subject – M sujeto
. culture – F cultura
. hair – M cabello
. coverage – F cobertura
. loss – F pérdida
. dad – M papá
. note – F nota
. activity – F actividad
. goal – M objetivo
. option – F opción
. gas – M gas
. region – F región
. population – F población
. ability – F capacidad
. resolution – F resolución
. employee – M empleado
. brain – M cerebro
. politician – M político
. middle – M centro
. storm – F tormenta
. generation – F generación
. critic – M crítico
. fan – M ventilador
. scientist – M científico
. target – M objetivo
. camp – M campamento
. afternoon – F tarde
. direction – F dirección
. science – F ciencia
. journalist – M periodista
. degree – M grado
. affair – M asunto
. damage – M daño
. strategy – F estrategia
. factor – M factor
. plant – F planta
. democracy – F democracia
. doubt – F duda
. solution – F solución
. spending – M gasto
. training – F formación
. abuse – M abuso
. danger – M peligro
. environment – M medio ambiente
. memory – F memoria
. nature – F naturaleza
. material – M material
. document – M documento
. income – M ingresos
. analyst – M analista
. play – M juego
. guard – F guardia
. hotel – M hotel
. editor – M editor
. missile – M misil
. accident – M accidente
. purpose – M propósito
. writer – M escritor
. emergency – F emergencia
. growth – M crecimiento
. bed – F cama
. welfare – M bienestar
. adult – M adulto
. faith – F fe
. proposal – F propuesta
. model – M modelo
. army – M ejército
. incident – M incidente
. box – F caja
. crowd – F multitud
. respect – M respeto
. department – M departamento
. access – M acceso
. date – F fecha
. chief – M jefe
. weather – M clima
. airport – M aeropuerto
. machine – F máquina
. window – F ventana
. agenda – M orden dM día
. advice – M consejo
. prosecution – F fiscalía
. conflict – M conflicto
. fall – F caída
. pilot – M piloto
. practice – F práctica
. track – F pista
. owner – M propietario
. increase – M aumento
. legislation – F legislación
. tree – M árbol
. debt – F deuda
. enemy – M enemigo
. truck – M camión
. lead – M plomo
. convention – F convención
. aid – F ayuda
. suicide – M suicidio
. quality – F calidad
. conservative – F conservadora
. size – M tamaño
. account – F cuenta
. pleasure – M placer
. institution – F institución
. airline – F línea aérea
. weight – M peso
. approach – M enfoque
. surgery – F cirugía
. holiday – F vacaciones
. start – M inicio
. victory – F victoria
. district – M distrito
. relation – F relación
. search – F búsqueda
. crew – F tripulación
. panel – M panel
. coalition – F coalición
. move – M movimiento
. package – M paquete
. check – M cheque
. minority – F minoría
. unit – F unidad
. bag – F bolsa
. surprise – F sorpresa
. focus – M foco
. circumstance – F circunstancia
. producer – M productor
. investment – F inversión
. ball – F pelota
. colleague – M colega
. resource – M recurso
. judgment – F sentencia
. background – M fondo
. union – F unión
. address – F dirección
. driver – M controlador
. hero – M héroe
. medicine – M medicamento
. representative – M representante
. vehicle – M vehículo
. commander – M comandante
. artist – M artista
. mayor – M alcalde
. run – F carrera
. ship – M barco
. theory – F teoría
. screen – F pantalla
. lesson – F lección
. resident – M residente
. partner – M socio
. bar – M bar
. ticket – M billete
. disaster – M desastre
. performance – M desempeño
. supporter – M aficionados
. killer – M asesino
. negotiation – F negociación
. sea – M mar
. wind – M viento
. shoe – M zapato
. secret – M secreto
. tragedy – F tragedia
. gift – M regalo
. tour – F gira
. manager – M gestor
. band – F banda
. birth – M nacimiento
. host – M anfitrión
. loan – M préstamo
. allegation – F alegación
. winner – M ganador
. religion – F religión
. article – M artículo
. session – F sesión
. being – M ser
. extent – F medida
. contract – M contrato
. sentence – F sentencia
. measure – F medida
. deputy – M diputado
. confidence – F confianza
. hell – M infierno
. relief – M alivio
. perspective – F perspectiva
. advantage – F ventaja
. scandal – M escándalo
. leg – F pierna
. restaurant – M restaurante
. dinner – F cena
. client – M cliente
. failure – M fracaso
. quarter – M trimestre
. element – M elemento
. claim – F reclamación
. property – F propiedad
. version – F versión
. attempt – M intento
. bus – M autobús
. customer – M cliente
. appeal – F apelación
. pound – F libra
. protection – F protección
. gene – M gen
. stone – F piedra
. opposition – F oposición
. apartment – M apartamento
. front – M frente
. female – F hembra
. prisoner – M prisionero
. black – M negro
. gang – F pandilla
. principle – M principio
. ally – M aliado
. adviser – M asesor
. visit – F visita
. bird – M pájaro
. stand – M soporte
. communication – F comunicación
. boat – M barco
. connection – F conexión
. key – F tecla
. strike – F huelga
. penalty – F pena
. warning – F advertencia
. luck – F suerte
. dna – M ADN
. spirit – M espíritu
. turn – F vuelta
. facility – F instalación
. teenager – M adolescente
. commitment – M compromiso
. item – M elemento
. procedure – M procedimiento de
. half – F media
. tank – M tanque
. telephone – M teléfono
. supply – M suministro
. attitude – F actitud
. block – M bloque
. bond – M vínculo
. style – M estilo
. football – M fútbol
. fuel – M combustible
. data – M datos
. glass – M cristal
. suit – M traje
. strength – F fuerza
. criticism – F críticas
. ice – M hielo
. equipment – M equipo
. promise – F promesa
. return – M regreso
. album – M álbum
. production – F producción
. corner – F esquina
. consequence – F consecuencia
. living – M vivos
. injury – F lesión
. cover – F tapa
. spot – M punto
. breast – F mama
. spring – F primavera
. controversy – F controversia
. destruction – F destrucción
. aspect – M aspecto
. club – M club
. aircraft – F aeronave
. firm – F empresa
. regime – M régimen
. competition – F competencia
. profit – M beneficio
. knowledge – M conocimiento
. spokesman – M portavoz
. review – F revisión
. understanding – F comprensión
. recession – F recesión
. singer – M cantante
. village – M pueblo
. arrest – F detención
. snow – F nieve
. joke – F broma
. gold – M oro
. contact – M contacto
. demand – F demanda
. task – F tarea
. hole – M agujero
. general – M general
. skin – F piel
. count – M recuento
. opponent – M oponente
. conclusion – F conclusión
. priority – F prioridad
. rape – F violación
. refugee – M refugiado
. mountain – F montaña
. summit – F cumbre
. bottom – F parte inferior
. management – F gestión
. commission – F comisión
. range – F gama
. code – M código
. cash – M dinero en efectivo
. mouth – F boca
. presence – F presencia
. share – F cuota
. fashion – F moda
. shape – F forma
. chair – F silla
. finger – M dedo
. fish – M pescado
. edition – F edición
. edge – M borde
. limit – M límite
. train – M tren
. belief – F creencia
. balance – M balance
. exchange – M interM cambio
. farm – F granja
. zone – F zona
. passenger – M pasajero
. lie – F mentira
. duty – M deber
. traffic – M tráfico
. horse – M caballo
. tradition – F tradición
. recovery – F recuperación
. inspector – M inspector
. difficulty – F dificultad
. file – M archivo
. birthday – M cumpleaños
. finance – F financiación
. crash – M accidente
. influence – F influencia
. regulation – F regulación
. analysis – M análisis
. struggle – F lucha
. heat – M calor
. dress – M vestido
. release – F liberación
. winter – M invierno
. virus – M virus
. theme – M tema
. notion – F noción
. device – M dispositivo
. anger – F ira
. english – M Inglés
. flag – F bandera
. context – M contexto
. wing – M ala
. fighting – M combates
. pattern – M patrón
. entertainment – M entretenimiento
. appearance – F aparición
. saving – M ahorro
. investor – M inversor
. bridge – M puente
. settlement – M asentamiento
. rain – F lluvia
. wood – F madera
. mail – M correo
. farmer – M agricultor
. mystery – M misterio
. prayer – F oración
. vision – F visión
. depression – F depresión
. explosion – F explosión
. defendant – M acusado
. structure – F estructura
. amendment – F enmienda
. assault – M asalto
. thinking – M pensamiento
. therapy – F terapia
. nurse – F enfermera
. path – M camino
. funding – F financiación
. tool – F herramienta
. title – M título
. housing – F carcasa
. shop – F tienda
. complaint – F queja
. wave – F ola
. cat – M gato
. map – M mapa
. employer – M empleador
. proof – F prueba
. emotion – F emoción
. skill – F habilidad
. trust – F confianza
. topic – M tema
. personality – F personalidad
. hall – F sala
. cabinet – M armario
. bone – M hueso
. soul – M alma
. chicken – M pollo
. location – F ubicación
. indication – F indicación
. speaker – M altavoz
. wage – M salario
. era – F era
. request – F solicitud
. boss – M jefe
. coach – M entrenador
. estate – F finca
. sector – M sector
. egg – M huevo
. stake – F estaca
. stop – F parada
. ring – M anillo
. shock – M choque
. contribution – F contribución
. announcement – M anuncio
. cigarette – M cigarrillo
. kitchen – F cocina
. territory – M territorio
. command – M comando
. island – F isla
. protest – F protesta
. impression – F impresión de
. fault – M fallo
. coast – F costa
. reading – F lectura
. variety – F variedad
. revenue – M ingresos
. bell – F campana
. coffee – M café
. alcohol – M alcohol
. lunch – M almuerzo
. expectation – F expectativa
. grade – M grado
. diet – F dieta
. section – F sección
. ear – M oído
. sky – M cielo
. assistance – F ayuda
. signal – F señal
. stress – M estrés
. alternative – F alternativa
. researcher – M investigador
. cable – M cable
. opening – F apertura
. beach – F playa
. volunteer – M voluntario
. burden – F carga
. detective – M detective
. toy – M juguete
. gain – F ganancia
. asset – M activo
. pool – F piscina
. trend – F tendencia
. survey – F encuesta
. planet – M planeta
. river – M río
. identity – F identidad
. ocean – M océano
. joy – F alegría
. delay – M retraso
. clinic – F clínica
. yard – M patio
. tip – F punta
. divorce – M divorcio
. sun – M sol
. row – F fila
. phrase – F frase
. worth – F pena
. collection – F colección
. occasion – F ocasión
. surface – F superficie
. tie – M empate
. musician – M músico
. concept – M concepto
. tension – F tensión
. outcome – M resultado
. approval – F aprobación
. fellow – M becario
. beauty – F belleza
. casualty – M siniestro
. copy – F copia
. mine – F mina
. watch – M reloj
. sleep – M sueño
. average – F media
. travel – M recorrido
. fraud – M fraude
. category – F categoría
. exercise – M ejercicio
. conviction – F convicción
. initiative – F iniciativa
. technique – F técnica de
. recording – F grabación
. sight – F vista
. reduction – F reducción
. whole – M conjunto
. corporation – F corporación
. passion – F pasión
. funeral – M funeral
. youth – F juventud
. instrument – M instrumento
. distance – F distancia
. desert – M desierto
. anniversary – M aniversario
. writing – F escritura
. invasion – F invasión
. compromise – M compromiso
. illness – F enfermedad
. tear – M desgarro
. gate – F puerta
. forest – M bosque
. experiment – M experimento
. golf – M golf
. talent – M talento
. post – M cargo
. gap – F brecha
. priest – M sacerdote
. novel – F novela
. division – F división
. desire – M deseo
. hat – M sombrero
. mortgage – F hipoteca
. reputation – F reputación
. score – F puntuación
. shoulder – M hombro
. relative – F relación
. column – F columna
. payment – M pago
. transition – F transición
. award – M premio
. capability – F capacidad
. definition – F definición
. pocket – M bolsillo
. speed – F velocidad
. concert – M concierto
. climate – M clima
. clue – F clave
. beer – F cerveza
. nose – F nariz
. green – M verde
. garden – M jardín
. satellite – M satélite
. ceremony – F ceremonia
. human – F humana
. discovery – M descubrimiento
. ride – M paseo
. root – F raíz
. tea – M té
. motion – M movimiento
. percentage – M porcentaje
. combination – F combinación
. explanation – F explicación
. scale – F escala
. chain – F cadena de
. twin – M gemelo
. capacity – F capacidad
. dealer – M distribuidor
. touch – M toque
. journey – M viaje
. delegate – M delegado
. link – M enlace
. plastic – M plástico
. stimulus – M estímulo
. cap – F tapa
. roll – M rollo
. construction – F construcción
. intention – F intención
. dispute – F disputa
. mood – M estado de ánimo
. design – M diseño
. childhood – F infancia
. engine – M motor
. lifetime – M tiempo de vida
. nightmare – F pesadilla
. dance – F danza
. meal – F comida
. offer – F oferta
. obligation – F obligación
. advance – M avance
. charity – F caridad
. tourist – M turista
. factory – F fábrica
. fat – F grasa
. salt – F sal de
. neck – M cuello
. bedroom – M dormitorio
. episode – M episodio
. engineer – M ingeniero
. punishment – M castigo
. testing – F pruebas
. instance – F instancia
. prospect – F perspectiva
. shopping – F compras
. smoke – M humo
. meat – F carne
. hold – F bodega
. retirement – F jubilación
. inflation – F inflación
. drama – M drama
. desk – M escritorio
. salary – M salario
. bible – F biblia
. grant – F subvención
. demonstration – F demostración
. dialogue – M diálogo
. substance – F sustancia
. core – M núcleo
. treaty – M tratado
. personnel – M personal
. sample – F muestra
. tactic – F táctica
. method – M método
. noise – M ruido
. objective – M objetivo
. flower – F flor
. cup – F copa
. temperature – F temperatura
. symbol – M símbolo
. revolution – F revolución
. taste – M sabor
. museum – M museo
. profile – M perfil
. suggestion – F sugerencia
. route – F ruta
. tooth – M diente
. consultant – M consultor
. drive – F unidad
. disorder – M trastorno
. sugar – M azúcar
. rise – M aumento
. chip – M chip
. motive – M motivo
. shirt – F camisa
. port – M puerto
. potential – M potencial
. schedule – M calendario
. parliament – M parlamento
. contest – M concurso
. atmosphere – F atmósfera
. branch – F rama
. estimate – F estimación
. symptom – M síntoma
. involvement – F participación
. discrimination – F discriminación
. heaven – M cielo
. walk – F caminata
. operator – M operador
. recommendation – F recomendación
. rebel – M rebelde
. round – F ronda
. maker – M fabricante
. wine – M vino
. remark – F observación
. mess – M lío
. tone – M tono
. resistance – F resistencia
. importance – F importancia
. exception – F excepción
. platform – F plataforma
. knife – M cuchillo
. perception – F percepción
. fee – F cuota
. master – M maestro
. circle – M círculo
. manner – F forma
. jet – M chorro
. meaning – M significado
. assessment – F evaluación
. plate – F placa
. expense – F expensas
. plot – F trama
. classroom – M aula
. brand – F marca
. painting – F pintura
. roof – M techo
. privilege – M privilegio
. drink – F bebida
. ban – F prohibición
. content – M contenido
. chemical – M producto químico
. french – M francés
. inspection – F inspección
. incentive – M incentivo
. piano – M piano
. bottle – F botella
. waste – M residuos
. error – M error
. label – F etiqueta
. clock – M reloj
. cream – F crema
. good – M bien
. phase – F fase de
. philosophy – F filosofía
. conduct – F conducta
. cycle – M ciclo
. electricity – F electricidad
. bishop – M obispo
. reader – M lector
. pregnancy – M embarazo
. league – F liga
. pet – F mascota
. foundation – F fundación
. boom – M boom
. tower – F torre
. feature – F característica
. withdrawal – F retirada
. breath – F respiración
. crack – F grieta
. manufacturer – M fabricante
. specialist – M especialista
. reference – F referencia
. tale – M cuento
. provision – F provisión
. historian – M historiador
. wire – M alambre
. speculation – F especulación
. pair – M par
. excuse – F excusa
. chocolate – M chocolate
. celebration – F celebración
. cheese – M queso
. fortune – F fortuna
. bathroom – M cuarto de baño
. function – F función de
. universe – M universo
. channel – M canal
. smile – F sonrisa
. milk – F leche
. requirement – M requisito
. suspicion – F sospecha
. household – M hogar
. finding – M hallazgo
. chest – M pecho
. routine – F rutina
. consideration – F consideración
. library – F biblioteca
. harm – M daño
. margin – M margen
. object – M objeto
. guitar – F guitarra
. button – M botón
. silence – M silencio
. improvement – F mejora
. drop – F caída de
. appointment – M nombramiento
. businessman – M hombre de negocios
. flow – M flujo
. metal – M metal
. mirror – M espejo
. present – F presente
. carrier – M portador
. expression – F expresión
. fate – M destino
. cloud – F nube
. muscle – M músculo
. belt – M cinturón
. chapter – M capítulo
. string – F cadena de
. trading – M comercio
. trick – M truco
. guide – F guía
. volume – M volumen
. match – M partido
. fantasy – F fantasía
. knee – F rodilla
. compound – M compuesto
. stomach – M estómago
. height – F altura
. draft – M proyecto
. stranger – M desconocido
. infection – F infección
. mass – F masa
. discipline – F disciplina
. fruit – M fruto
. visitor – M visitante
. poem – M poema
. phenomenon – M fenómeno
. fence – F valla
. application – F aplicación
. recipe – F receta
. clothing – F ropa
. guilt – F culpa
. survival – F supervivencia
. champion – M campeón
. uniform – M uniforme
. print – F impresión
. potato – F papa
. arrangement – F disposición
. moon – F luna
. bear – M oso
. wound – F herida
. stability – F estabilidad
. pride – M orgullo
. restriction – F restricción
. total – M total
. barrier – F barrera
. cousin – M primo
. occupation – F ocupación
. silver – F plata
. cake – F torta
. lung – M pulmón
. wheel – F rueda
. observer – M observador
. tune – F melodía
. description – F descripción
. establishment – M establecimiento
. chamber – F cámara de
. horror – M horror
. banking – F banca
. apple – F manzana
. implication – F implicación
. steel – M acero
. throat – F garganta
. essence – F esencia
. raid – F incursión
. distinction – F distinción
. german – M alemán
. lip – M labio
. timing – F temporización
. insight – F visión
. coup – M golpe de Estado
. shift – M M cambio
. policeman – M policía
. habit – M hábito
. sheet – F hoja de
. offender – M delincuente
. midnight – F medianoche
. execution – F ejecución
. anxiety – F ansiedad
. enterprise – F empresa
. strip – F tira
. pop – M pop
. wonder – F maravilla
. shadow – F sombra
. liberty – F libertad
. fiction – F ficción
. intervention – F intervención
. creation – F creación
. marketing – F comercialización
. christian – M cristiano
. pot – F olla
. fishing – F pesca
. breakfast – M desayuno
. tube – M tubo
. determination – F determinación
. sand – F arena
. permission – M permiso
. guideline – F directriz
. shame – F vergüenza
. riot – M disturbios
. user – M usuario
. organ – M órgano
. resort – M resort
. designer – M diseñador
. comparison – F comparación
. employment – M empleo
. bread – M pan
. wish – M deseo
. lover – M amante
. jacket – F chaqueta
. pass – M pase
. statute – M estatuto
. pace – M ritmo
. frame – F trama
. confusion – F confusión
. guarantee – F garantía
. commissioner – M comisionado
. flame – F llama
. assumption – F asunción
. graduate – M graduado
. entry – F entrada
. ward – F sala
. win – F victoria
. opera – F ópera
. friendship – F amistad
. exposure – F exposición
. pig – M cerdo
. mate – M mate
. nerve – M nervio
. length – F longitud
. cow – F vaca
. pack – M paquete
. instruction – F instrucción
. collapse – M colapso
. assistant – M asistente
. objection – F objeción
. diary – M diario
. scholar – M erudito
. comfort – F comodidad
. preparation – F preparación
. province – F provincia
. passage – M pasaje
. crystal – M cristal
. gear – M engranaje
. stroke – M trazo
. decline – F disminución
. achievement – M logro
. existence – F existencia
. alliance – F alianza
. profession – F profesión
. delivery – F entrega
. publisher – M editor
. sympathy – F simpatía
. dish – M plato
. worry – F preocupación
. component – M componente
. adventure – F aventura
. crop – M cultivo
. blow – M golpe
. sake – M aras
. sin – M pecado
. pension – F pensión
. garage – M garaje
. radiation – F radiación
. juice – M jugo
. setting – M ajuste
. index – M índice
. vegetable – M vegetal
. partnership – F asociación
. poetry – F poesía
. recognition – M reconocimiento
. self – M auto
. standing – M pie
. tissue – M tejido
. shell – F concha
. captain – M capitán
. grave – F tumba
. rank – M rango
. gender – M género
. shortage – F escasez
. prize – M premio
. coat – F capa
. seed – F semilla
. rat – F rata
. soil – M suelo
. shore – F orilla
. defeat – F derrota
. notice – F notificación
. boot – F bota
. chart – M gráfico
. ministry – M ministerio
. diamond – M diamante
. finish – M acabado
. admission – F admisión
. dark – F oscuridad
. laboratory – M laboratorio
. professional – M profesional
. reward – F recompensa
. infant – M bebé
. text – M texto
. shower – F ducha
. dose – F dosis
. panic – M pánico
. net – F red
. clerk – M secretario
. miner – M minero
. delegation – F delegación
. imagination – F imaginación
. unity – F unidad
. uncle – M tío
. ingredient – M ingrediente
. assignment – F asignación
. currency – F moneda
. battery – F batería
. tunnel – M túnel
. resignation – F renuncia
. buyer – M comprador
. bike – F moto
. excitement – F emoción
. mouse – M ratón
. alarm – F alarma
. poet – M poeta
. landscape – M paisaje
. selection – F selección
. cry – M grito
. separation – F separación
. display – F pantalla
. disability – F discapacidad
. counter – M contador
. championship – M campeonato
. butter – F mantequilla
. portrait – M retrato
. stick – M palo
. engineering – F ingeniería
. myth – M mito
. essay – M ensayo
. cold – M frío
. coal – M carbón
. contrast – M contraste
. observation – F observación
. tail – F cola
. mechanism – M mecanismo
. scheme – M esquema
. presentation – F presentación
. angel – M ángel
. bonus – M bono
. possession – F posesión
. learning – M aprendizaje
. teaching – F enseñanza
. deck – F cubierta
. creature – F criatura
. running – M funcionamiento
. literature – F literatura
. weakness – F debilidad
. blue – M azul
. engagement – M compromiso
. uncertainty – F incertidumbre
. inquiry – F investigación
. motivation – F motivación
. dust – M polvo
. peak – M pico
. instinct – M instinto
. needle – F aguja
. leaf – F hoja
. launch – M lanzamiento
. laugh – F risa
. leave – F licencia
. grass – F hierba
. iron – M hierro
. competitor – M competidor
. complex – M complejo
. bean – M frijol
. pole – M polo
. vessel – M buque
. subsidy – F subvención
. bid – F oferta
. landing – M aterrizaje
. pipe – F tubería
. interpretation – F interpretación
. tournament – M torneo
. hip – F cadera
. diagnosis – M diagnóstico
. pitch – M terreno de juego
. journal – F revista
. ceiling – M techo
. export – F exportación
. awareness – F conciencia
. cross – F cruz
. kiss – M beso
. examination – M examen
. empire – M imperio
. replacement – F sustitución
. duck – M pato
. formula – F fórmula
. devil – M diablo
. limitation – F limitación
. compensation – F compensación
. invitation – F invitación
. declaration – F declaración
. significance – M significado
. final – F final
. premium – F prima
. ambulance – F ambulancia
. carpet – F alfombra
. temple – M templo
. constituent – M constituyente
. concession – F concesión
. consent – M consentimiento
. premise – F premisa
. heritage – M patrimonio
. shelf – M estante
. hint – F indirecta
. rhythm – M ritmo
. liability – M pasivo
. heel – M talón
. layer – F capa de
. strain – F cepa
. carbon – M carbono
. forum – M foro
. merit – M mérito
. youngster – M joven
. transfer – F transferencia
. distribution – F distribución
. expansion – F expansión
. depth – F profundidad
. blanket – F manta
. kingdom – M reino
. mud – M barro
. arrival – F llegada
. reflection – M reflejo
. envelope – F envoltura
. reserve – F reserva
. hunting – F caza
. furniture – M muebles
. gesture – M gesto
. residence – F residencia
. ambition – F ambición
. nail – F uña
. spectrum – M espectro
. drawing – M dibujo
. enthusiasm – M entusiasmo
. pen – F pluma
. preference – F preferencia
. absence – F ausencia
. oxygen – M oxígeno
. squad – F escuadra
. pollution – F contaminación
. lock – F cerradura
. extension – F extensión
. participant – M participante
. architect – M arquitecto
. bench – F magistratura
. rope – F cuerda
. aim – M objetivo
. stream – F corriente de
. evolution – F evolución
. angle – M ángulo
. jurisdiction – F jurisdicción
. charter – F carta
. ideology – F ideología
. tide – F marea
. representation – F representación
. identification – F identificación
. concentration – F concentración
. norm – F norma
. spread – F propagación
. rival – M rival
. disappointment – F decepción
. tribunal – M tribunal
. grain – M grano
. proportion – F proporción
. fool – M tonto
. merger – F fusión
. loyalty – F lealtad
. publication – F publicación
. participation – F participación
. escape – M escape
. shareholder – M accionista
. constituency – F circunscripción
. paint – F pintura
. toilet – M inodoro
. ghost – M fantasma
. attraction – F atracción
. lion – M león
. craft – F nave
. custom – F costumbre
. cliff – M acantilado
. palace – M palacio
. grip – F empuñadura
. protein – F proteína
. accuracy – F exactitud
. theft – M robo
. widow – F viuda
. acceptance – F aceptación
. accent – M acento
. smell – M olor
. departure – F salida
. membership – M miembros
. expertise – F experiencia
. repair – F reparación
. assembly – F asamblea
. summary – M resumen
. logic – F lógica
. boundary – M límite
. equivalent – M equivalente
. holder – M titular
. dimension – F dimensión
. rail – M riel
. transaction – F transacción
. left – F izquierda
. sequence – F secuencia
. festival – M festival
. pit – M pozo
. horizon – M horizonte
. bowl – M cuenco
. purchase – F compra
. plaintiff – M demandante
. aunt – F tía
. equity – F equidad
. load – F carga
. scope – M alcance
. darkness – F oscuridad
. sandwich – M sándwich
. parish – F parroquia
. closure – M cierre
. pile – F pila
. ownership – F propiedad
. origin – M origen
. defender – M defensor
. circuit – M circuito de
. introduction – F introducción
. mode – M modo de
. discount – M descuento
. equation – F ecuación
. entity – F entidad
. kit – M kit
. psychology – F psicología
. virtue – F virtud
. flexibility – F flexibilidad
. trainer – M entrenador
. continent – M continente
. trader – M comerciante
. bath – M baño
. brick – M ladrillo
. indicator – M indicador
. seller – M vendedor
. promotion – F promoción
. clash – M choque
. characteristic – F característica
. coin – F moneda
. assurance – F garantía
. proposition – F proposición
. tongue – F lengua
. minimum – M mínimo
. collector – M colector
. capitalism – M capitalismo
. basket – F cesta
. framework – M marco
. consciousness – F conciencia
. switch – M interruptor
. rent – M alquiler
. curve – F curva
. cotton – M algodón
. patch – M parche
. import – F importación
. isolation – M aislamiento
. entrance – F entrada
. necessity – F necesidad
. square – F plaza
. venture – F empresa
. steam – M vapor
. agriculture – F agricultura
. transformation – F transformación
. sheep – F ovejas
. brush – M cepillo
. database – F base de datos
. deposit – M depósito
. menu – M menú
. adjustment – M ajuste
. triumph – M triunfo
. consumption – M consumo
. guardian – M guardián
. curtain – F cortina
. satisfaction – F satisfacción
. calculation – M cálculo
. fleet – F flota
. remedy – M remedio
. lane – M carril
. certificate – M certificado
. swimming – F natación
. emission – F emisión
. fabric – F tela
. medium – M medio
. efficiency – F eficiencia
. interaction – F interacción
. cab – F cabina
. easter – F Pascua
. glory – F gloria
. reception – F recepción
. productivity – F productividad
. acid – M ácido
. servant – M siervo
. evaluation – F evaluación
. mill – M molino
. exhibition – F exposición
. sum – F suma
. counterpart – F contraparte
. sergeant – M sargento
. storage – M almacenamiento
. fraction – F fracción
. innovation – F innovación
. stance – F postura
. motor – M motor
. format – M formato
. particle – F partícula
. trace – F traza
. fluid – M fluido
. curriculum – M plan de estudios
. doctrine – F doctrina
. developer – M desarrollador
. pause – F pausa
. removal – F eliminación
. sensation – F sensación
. dividend – M dividendo
. monopoly – M monopolio
. gallery – F galería
. lecture – F conferencia
. taxi – M taxi
. discretion – F discreción
. flesh – F carne
. merchant – M comerciante
. quantity – F cantidad
. darling – M niño mimado
. justification – F justificación
. painter – M pintor
. mixture – F mezcF de
. breach – M incumplimiento
. lift – M ascensor
. pond – M estanque
. cheek – F mejilla
. successor – M sucesor
. registration – M registro
. consultation – F consulta
. qualification – F calificación
. supplier – M proveedor
. autumn – M otoño
. hardware – M hardware
. leather – M cuero
. rabbit – M conejo
. paragraph – M párrafo
. companion – M compañero
. bulk – F mayor parte
. corridor – M corredor
. workshop – M taller
. shade – F sombra
. accountant – M contador
. sword – F espada
. formation – F formación
. integration – F integración
. expenditure – M gastos
. input – F entrada
. rod – F varilla
. complexity – F complejidad
. skirt – F falda
. insect – M insecto
. transport – M transporte
. mortality – F mortalidad
. slope – F pendiente
. restoration – F restauración
. nest – M nido
. variation – F variación
. composition – F composición
. crown – F corona
. probability – F probabilidad
. liberation – F liberación
. attendance – F asistencia
. organism – M organismo
. conservation – F conservación
. sculpture – F escultura
. champagne – M champagne
. architecture – F arquitectura
. other – M otro
. lord – M señor
. tv – F tv
. van – F furgoneta
. directory – M directorio
. hundred – M cien
. dozen – F docena
. treasury – F tesorería
. petrol – F gasolina
. purchaser – M comprador
. terrace – F terraza
. avenue – F avenida
. thousand – M mil
. sociology – F sociología
. inn – F posada
. colony – F colonia
. association – F asociación
. prince – M príncipe
. corp – F corp
. lad – M muchacho
. catalogue – M catálogo
. magistrate – M magistrado
. allocation – F asignación
. harbour – M puerto
. solicitor – M abogado
. traveller – M viajero
. earl – M conde
. humour – M humor
. pope – M Papa
. mrs – F señora
. behaviour – M comportamiento
. bill – M proyecto de ley
. mark – F marca
. criterion – M criterio
. duke – M duque
. red – F roja
. federation – F federación
. jew – M judio
. colonel – M coronel
. shit – F mierda
. eagle – M águila
. centre – M centro
. miss – F señorita
. fig – M higo
. institute – M instituto
. bay – F bahía
. honour – M honor
. classification – F clasificación
. councillor – M concejal
. constable – M alguacil
. bureau – F oficina
. mile – F milla
. proceeding – M procedimiento
. judgement – F sentencia
. cheque – M cheque
. no – F no
. queen – F reina
. valley – M valle
. billion – M mil millones
. inch – F pulgada
. stairs – F escaleras
. fibre – F fibra
. acre – M acre
. white – M blanco
. lake – M lago
. god – M dios
. enquiry – F investigación
. princess – F princesa
. rubbish – F basura
. tonne – F tonelada
. navy – F marina
. chap – M cap
. million – M millón
. programme – M programa
. organisation – F organización
. republic – F república
. percent – M porcentaje
. mummy – F momia
. favourite – M favorito
. cm – M cm
. illustration – F ilustración
. tory – F his-
. aids – F ayudas
. theatre – M teatro
. licence – F licencia
. metre – M metro
. constitution – F constitución
. junction – F unión
. interface – F interfaz
. gaze – F mirada
. pensioner – M pensionista
. builder – M constructor
. university – F universidad
. park – M parque
. hill – F colina
. neighbour – M vecino
. unix – M unix
. favour – M favor
. borough – F ciudad
. redundancy – F redundancia
. king – M rey
. co – F co
. ref – M árbitro
. lifespan – F vida útil
. abbey – F abadía
. rumour – M rumor
. cupboard – M armario
. council – M ayuntamiento
. colour – M color
. dollar – M dólar
. commonwealth – F mancomunidad
. county – M condado
. mum – F momia
. rose – F rosa
. vat – F cuba
. photo – F foto
. lorry – M camión
. labour – F mano de obra
. defence – F defensa
. earth – F tierra
. flat – F plana
. offence – M delito
. daddy – M papá
. appendix – M apéndice
. whisky – M whisky
. isle – F isla
. go – F marcha
. villa – F villa
. tutor – M tutor
. archbishop – M arzobispo
. photograph – F fotografía
. specification – F especificación
. polytechnic – F politécnica
. bush – F zarza
. frequency – F frecuencia
. seminar – M seminario
. interior – M interior
. verse – M verso
. receipt – M recibo
. breed – F raza
. measurement – F medición
. palm – F palma
. dock – M muelle
. pc – M pc
. disadvantage – F desventaja
. installation – F instalación
. advertisement – M anuncio
. implementation – F implementación
. portfolio – F cartera
. timber – F madera
. clause – F cláusula
. discourse – M discurso
. disc – M disco
. blade – F cuchilla
. ratio – F relación
. mineral – M mineral
. outline – M contorno
. addition – F adición
. machinery – F maquinaria
. canal – M canal
. local – M local
. disposal – F eliminación
. refusal – F negativa
. domain – M dominio
. register – M registro
. audit – F auditoría
. availability – F disponibilidad
. acquisition – F adquisición
. autonomy – F autonomía
. silk – F seda
. beam – M haz
. accommodation – M alojamiento
. applicant – M solicitante
. modification – F modificación
. tin – M estaño
. fragment – M fragmento
. tenant – M inquilino
. conversion – F conversión
. vendor – M vendedor
. practitioner – M practicante
. delight – M deleite
. filter – M filtro
. bronze – M bronce
. doorway – F puerta
. incidence – F incidencia
. lease – M contrato de arrendamiento
. constraint – F restricción
. cloth – M paño
. nursery – M vivero
. creditor – M acreedor
. taxation – F imposición
. disk – M disco
. dictionary – M diccionario
. conception – F concepción
. trustee – M fiduciario
. molecule – F molécula
. holding – F celebración
. cottage – F casa de campo
. landlord – M arrendador
. succession – F sucesión
. warmth – M calor
. spell – M hechizo
. chapel – F capilla
. leisure – M ocio
. reign – M reinado
. reply – F respuesta
. duration – F duración
. castle – M castillo
. hierarchy – F jerarquía
. correlation – F correlación
. exclusion – F exclusión
. pub – M pub
. hypothesis – F hipótesis
. lamp – F lámpara
. sphere – F esfera
. chancellor – M canciller
. peasant – M campesino
. output – F salida
. emperor – M emperador
. glance – F mirada
. specimen – M espécimen
. directive – F directiva
. thesis – F tesis
. working – M trabajo
. oak – M roble
. turnover – M volumen de negocios
. allowance – M subsidio
. tray – F bandeja
. auditor – M auditor
. server – M servidor
. cathedral – F catedral
. pity – F piedad
. variable – F variable
. clay – F arcilla
. carriage – M carro
. cinema – M cine
. leaflet – M folleto
. copper – M cobre
. density – F densidad
. subsidiary – F filial
. dismissal – M despido
. completion – F finalización
. processor – M procesador
. packet – M paquete
. wool – F lana
. heading – M encabezamiento
. grammar – F gramática
. pavement – M pavimento
. receiver – M receptor
. module – M módulo
. railway – M ferrocarril
. pupil – F pupila
. cricket – M grillo
. printer – F impresora
. interval – M intervalo
. diagram – M diagrama
. bastard – M hijo de puta"""

def process(string):
    words = {}
    noun_string = string.replace('\n', '').replace('\xa0', '')
    noun_list = noun_string.split('.')

    for each in noun_list:
        processed = each.replace('\u2013 M ', '0').replace('\u2013 F ', '0')
        split = processed.split('0')

        words[split[1]] = {
                'pos': 'noun',
                'category': 'M' if ('M' in each) else 'F',
                'gloss': split[0],
                'regular': True
            }
    
    with open("wordlist.py", "w") as f:
        print("content = ", words, file=f)

if __name__ == '__main__':
    process(nouns)