verbs = """abrazar-hug,
abrir-open,
acabar-finish,
acabarde-have just,
acordar-agree upon,
acostar-go bed,
afeitar-shave oneself,
ahorrar-save money,
almorzar-eat lunch,
alquilar-rent,
amar-love,
añadir-add,
andar-walk,
aparecer-appear,
aplanar-throw out,
aplastar-flatten,
aprender-learn,
arrastrar-crawl,
arreglar-fix,
atacar-attack,
asistir-attend,
asustar-frighten,
aumentar-increase,
ayudar-help,
bailar-dance,
bañar-bathe,
barrer-sweep,
batir-whisk,
beber-drink,
besar-kiss,
borrar-erase,
bromear-joke,
bucear-dive,
burlar-make fun of,
buscar-look for,
calentar-heat,
calificar-grade,
caminar-walk,
cansar-tire,
cantar-sing,
casar-marry,
cazar-hunt,
celebrar-celebrate,
cenar-have dinner,
cepillar-brush,
cerrar-close,
charlar-chat,
chupar-suck,
cocinar-cook,
coger-catch,
comer-eat,
comprar-buy,
comprender-understand,
conducir-drive,
conocer-meet,
contar-relate,
contestar-answer,
correr-run,
cortar-cut,
costar-cost,
cuestar-cost,
crear-create,
creer-believe,
cuajar-curdle,
cubrir-cover,
cumplir-fulfill,
dar-give,
deber-should,
decidir-decide,
decir-say,
digir-say,
dicir-say,
dejar-leave,
desayunar-eat breakfast,
descansar-rest,
desear-wish,
deshacer-undo,
despedir-say goodbye,
despertar-wake up,
despiertar-wake up,
destruir-destroy,
detener-stop,
dirigir-lead,
disculpar-apologize for,
discutir-argue,
distinguir-distinguish,
divertir-have fun,
diviertir-have fun,
doler-hurt,
dueler-hurt,
dormir-sleep,
duermir-sleep,
duchar-shower,
echar-throw,
elegir-choose,
empeorar-worsen,
empezar-begin,
empiezar-begin,
empiecar-begin,
empujar-push,
enamorar-fall in love,
encantar-be delighted about,
encender-light,
enfermar-get sick,
enojar-be angry,
enseñar-teach,
entender-understand,
entrar-enter,
escuchar-listen,
escribir-write,
esperar-wait/hope,
esquiar-ski,
estar-be,
estudiar-study,
exportar-export,
fastidiar-annoy/tease,
felicitar-congratulate,
fingir-pretend,
finjir-pretend,
firmar-sign,
flipar-be crazy about,
freir-fry,
fusilar-execute by firing squad,
ganar-win,
gastar-spend,
gritar-shout,
guiar-lead,
gustar-be pleasing,
haber-have [aux],
hablar-talk,
hacer-do,
hager-do,
hallar-find,
helar-freeze,
herir-injure,
hinchar-anger,
huir-flee,
hundir-sink,
insultar-insult,
ir-go,
var-go,
invitar-invite,
injerir-inject/insert,
jalar-pull,
joder-fuck,
jugar-play,
jurar-swear,
juzgar-judge,
lastimar-hurt emotionally,
lavar-wash,
leer-read,
levantar-raise,
limpiar-clean,
llegar-arrive,
llevar-bring,
llorar-cry,
llover-rain,
lluever-rain,
lograr-accomplish,
luchar-fight,
manejar-drive,
matar-kill,
mejorar-get better,
meter-place inside,
mirar-look,
mojar-wet,
molestar-annoy,
morir-die,
muerir-die,
nacer-be born,
nazcer-be born,
nadar-swim,
necesitar-need,
negar-deny,
nevar-snow,
nievar-snow,
obtener-obtain,
obtenger-obtain,
obtiener-obtain,
odiar-hate,
ofrecer-offer,
ofrezcer-offer,
oír-hear,
oigir-hear,
oyir-hear,
oler-smell,
hueler-smell,
olvidar-forget,
operar-operate,
orar-pray,
pagar-pay,
parecer-appear,
parezcer-appear,
participar-participate,
partir-cut,
pasar-pass/happen,
pasear-ride/stroll,
pedir-ask for,
pidir-ask for,
peinar-comb,
pelear-fight,
pensar-think,
piensar-think,
perseguir-chase,
persiguir-chase,
pintar-paint,
pisar-step on,
planchar-iron,
platicar-chat,
poder-can/be able,
pueder-can/be able,
poner-put,
ponger-put,
practicar-practice,
preguntar-ask,
preparar-prepare,
prestar-lend,
quedar-stay,
quejar-complain,
quemar-burn,
querer-want,
quierer-want,
quitar-take away,
rasurar-shave oneself,
recibir-receive,
recordar-remember,
recuerdar-remember,
recoger-gather,
recojer-gather,
regalar-give [as a gift],
regresar-return,
reír-laugh,
ríir-laugh,
repartir-distribute,
resistir-bear,
rogar-pray beg,
romper-rip break,
saber-know,
sacar-take out,
salir-leave go out,
saludar-greet,
secar-dry,
sequar-dry,
seguir-follow,
sigir-follow,
siguir-follow,
sentar-sit,
sientar-sit,
sentir-feel,
sientir-feel,
significar-mean,
sonar-ring,
sonreír-smile,
sonríir-smile,
sonrojar-blush,
soñar-dream,
soportar-bear,
subir-go up,
temer-fear,
tener-have,
tenger-have,
tiener-have,
tentar-touch,
terminar-finish,
tirar-throw,
tocar-touch,
toquar-touch,
tomar-take,
trabajar-work,
traducir-translate,
traduzcir-translate,
tragar-swallow,
traer-bring,
traiger-bring,
usar-use,
utilizar-use,
vencer-defeat,
vender-sell,
venir-come,
vengir-come,
vienir-come,
ver-see,
veer-see,
viajar-travel,
visitar-visit,
vivir-live,
volver-return,
vuelver-return,
yacer-lie,
zafar-untie,
zanjar-resolve"""

def process(some_string):
    processed = some_string.replace('\n', '').split(',')
    words = {}

    for each_entry in processed:
        each = each_entry.split('-')
        category = each[0][-2:]
        stem = each[0][:-2]
        gloss = each[1]

        words[stem] = {
                'pos': 'verb',
                'category': category,
                'gloss': gloss,
                'regular': True
            }
    
    with open("verblist.py", "w") as f:
        print(words, file=f)

if __name__ == '__main__':
    process(verbs)
